### ISSUE TITLE
Caching improvements

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/TSDemoBoard#2]
## Improvements
1. **Cache invalidation**: A more fully developed caching strategy would have a way to invalidate the cache. One way to do that here would be to record the file system timestamps of the code and check to see if they changed. If so, throw a flag to refresh.

**Comment by chrisroederucdenver** [comment]
Respectfully, we should consider removing the cache and closing this ticket.

**Comment by joeflack4** [comment]
@chrisroederucdenver Up to you! I haven't been using this much. The cache doesn't get committed, and it speeds things up if you want to do debugging or share some results with more emphasis on sharing speed / ease than being up-to-date. But I don't remember how useful it was to me. I do plan on coming back to this repo more when I'm closer to the end of my current workload.

**Comment by chrisroederucdenver** [comment]
I'm wary of that feature because it hides the performance issues, and may hide bugs too. With the install scripts in order, we are able to run locally when we really need snappy performance during development. #lesscodeisbetter
